[package]
published-at = "0xf634125d018ebe6f831b9e486510d0063710d8e08658bbb16ed62adc3a7743da"
name = "Switchboard"
edition = "2024.beta"
version = "0.0.2"

# # mainnet
# [dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
switchboard = "0x0"
